manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mjw6i
      url-base: https://github.com/mjw6i
    - name: genteure
      url-base: https://github.com/Genteure
  projects:
    - name: zmk
      remote: genteure
      revision: fix/stm32-hash-redefine
      import: app/west.yml
  self:
    path: config
